### PR TITLE
Fix vote_cache

### LINKED ISSUE #1206: Fix `mdb_store::flush()`
we swap the vote cache before writing it to disk

### PR DESCRIPTION
**Pull request by PlasmaPower**
This adds a second cache layer, so that the vote store remains consistent during flushing.

Fixes #1206

### CODE REVIEW

File: rai/node/lmdb.cpp [hunk 1]
```diff
@@ -1829,12 +1829,12 @@ void rai::mdb_store::checksum_del (rai::transaction const & transaction_a, uint6
 
 void rai::mdb_store::flush (rai::transaction const & transaction_a)
 {
-	std::unordered_map<rai::account, std::shared_ptr<rai::vote>> sequence_cache_l;
 	{
 		std::lock_guard<std::mutex> lock (cache_mutex);
-		sequence_cache_l.swap (vote_cache);
+		vote_cache_l2 = vote_cache_l1;
```
Comment (clemahieu) [inline rai/node/lmdb.cpp]: Since we're checking both l1 and l2, do we need to copy this, it seems like a swap would still work.
At the end of the for-look that checks l2 we could clear l2.

File: rai/node/lmdb.cpp [hunk 2]
```diff
@@ -1829,12 +1829,12 @@ void rai::mdb_store::checksum_del (rai::transaction const & transaction_a, uint6
...
+		vote_cache_l1.clear ();
 	}
-	for (auto i (sequence_cache_l.begin ()), n (sequence_cache_l.end ()); i != n; ++i)
+	for (auto i (vote_cache_l2.begin ()), n (vote_cache_l2.end ()); i != n; ++i)
```
Comment (clemahieu) [inline rai/node/lmdb.cpp]: Actually accessing l2 here isn't safe because cache_mutex is no longer locked.

Comment (PlasmaPower) [reply rai/node/lmdb.cpp]: It's indeed safe because the function won't be called concurrently, and the function is the only place where it's written to.

File: rai/node/lmdb.cpp (hunk 1 above)
Comment (PlasmaPower) [reply rai/node/lmdb.cpp]: > Since we're checking both l1 and l2, do we need to copy this, it seems like a swap would still work.
Yeah good point.

>  At the end of the for-look that checks l2 we could clear l2.
I believe that would result in worse performance. Also, we'd need to do it after the transaction expires, not at the end of the function.

File: rai/node/lmdb.cpp (hunk 2 above)
Comment (clemahieu) [reply rai/node/lmdb.cpp]: Good point, looks right.

Comment (clemahieu) [reply rai/node/lmdb.cpp]: Good point, looks right.
